apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}